import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import styles from '@/styles/app/layout.module.scss';
import './globals.css';

export const metadata = {
  title: 'personal blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body style={{ background: 'var(--bg-main)' }}>
        <Sidebar />
        <main className={styles.main}>
          <Header />
          <section className={styles.section}>{children}</section>
        </main>
      </body>
    </html>
  );
}
