'use client';
import ModalWrap from '@/components/modal/ModalWrap';
import './globals.css';
import { RecoilRoot, useRecoilState } from 'recoil';

export const metadata = {
  title: 'personal blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <RecoilRoot>
        <body style={{ background: 'var(--bg-main)' }}>
          {children}
          <ModalWrap />
        </body>
      </RecoilRoot>
    </html>
  );
}
