import ModalWrap from '@/components/modal/ModalWrap';
import './globals.css';
import { Providers } from '@/utils/redux/Providers';

export const metadata = {
  title: 'personal blog',
  description: 'Generated by create next app',

  //<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <Providers>
        <body style={{ background: 'var(--bg-main)' }}>
          {children}
          <ModalWrap />
        </body>
      </Providers>
    </html>
  );
}
